;;; mb-search-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from mb-search.el

(autoload 'mb-search-artist "mb-search" "\


(fn ARTIST)" t)
(autoload 'mb-search-release-group "mb-search" "\


(fn RELEASE-GROUP)" t)
(autoload 'mb-search-work "mb-search" "\


(fn WORK)" t)
(autoload 'mb-search-release "mb-search" "\


(fn RELEASE)" t)
(register-definition-prefixes "mb-search" '("mb-api-"))

;;; End of scraped data

(provide 'mb-search-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mb-search-autoloads.el ends here
